spring.application.name=gateway-service
server.port=8888

spring.cloud.config.enabled=false

# Eureka Client Configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/conference-realm
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

spring.security.oauth2.client.registration.keycloak.client-id=conference-gateway
spring.security.oauth2.client.registration.keycloak.client-secret=DUoSnK5zRYiTWgPX7wIQaXc7ShHIIL0c
spring.security.oauth2.client.registration.keycloak.scope[0]=openid
spring.security.oauth2.client.registration.keycloak.scope[1]=profile
spring.security.oauth2.client.registration.keycloak.scope[2]=email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/conference-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/conference-realm/protocol/openid-connect/certs
