version: "3.9"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-conf-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data